# Configurações do site
title: Cyber Coffe
SEOTitle: Cyber Coffe
header-img: img/home-bg.jpg
email: felipedasvrosa@hotmail.com
description: "Profissional em Cibersegurança com expertise em Análise de Vulnerabilidades, Administração, Suporte técnico e Segurança Ofensiva."
keyword: "Felipe da Silva Rosa, Cibersegurança, Segurança da Informação, Pentest, Análise de Vulnerabilidades, Red Team, Blue Team"
url: "https://felipedasilvarosa.github.io" # Substitua pelo seu host real
baseurl: "" # por exemplo, '/blog' se o seu blog estiver hospedado em 'host/blog'

# Publicar posts ou documentos de coleção com uma data futura.
future: true

# Configurações de redes sociais
RSS: false
github_username: felinux0x
twitter_username: c0rvo_pwn
#facebook_username:  huxpro
linkedin_username:  felipe0x01

# Configurações de compilação
# a partir de 2016, 'pygments' não é suportado no GitHub Pages. Use 'rouge' para realce de sintaxe.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # se você quiser personalizar a âncora. confira a linha:181 de `post.html`
# Se você tiver problemas com fuso horário (por exemplo, #68) na China, descomente para usar isto:
#timezone: CN

# Gems
# do PR#40, para suportar a visualização local para Jekyll 3.0
# certifique-se de ter esta gem instalada
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Configurações de Markdown
# substitui redcarpet por kramdown,
# embora o redcarpet possa realçar o código automaticamente, a falta de id de cabeçalho torna o catálogo impossível, então mudei para kramdown
# documento: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !importante
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Configurações do Disqus
disqus_username: c0rvo

# Configurações do Netease
netease_comment: false

# Configurações de Analytics
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id:  # Formato: UA-xxxxxx-xx
# ga_domain: 

# Configurações da barra lateral
sidebar: true # se deve ou não usar a barra lateral.
sidebar-about-description: "Atuar em Segurança da Informação com foco em Análise de Vulnerabilidades, Pentest, Controle de Acesso, Incidentes de Segurança e Administração de sistemas."
sidebar-avatar: https://github.com/felinux0x.png # use URL absoluta, pois é usada em `/` e `/about/`

# Tags em Destaque
featured-tags: true # se deve ou não usar Tags em Destaque
featured-condition-size: 1 # Uma tag aparecerá em destaque se o número de posts com ela for maior que este valor

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Renderização MathJax para layout:page (ex: visualização de post)
page-mathjax: false

# Amigos
friends:
  [

  ]
